version: '3.2'
networks:
  kong-net:
    external: false


    

services:


  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    volumes:
      - type : volume
        source: pgdata
        target: /var/lib/postgresql/data
        
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kong

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=password
    depends_on:
      - kong-database
  

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong
    restart: always
    networks:
      - kong-net
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=password
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - kong-migration
      - kong-database
    ports:
      - "8000:8000"

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    restart: always
    networks:
      - kong-net
    volumes:
      - type : volume
        source: pgdata
        target: /app/kongadata
    depends_on:
      - kong-database
    ports:
      - "1337:1337"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    depends_on:
      - kong-database
      - kong-migration
      - kong
      # - konga-prepare
      - konga
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - kong-net
  
  appointment_service:
    build: ./appointment_service
    image: appointment_service:1.0.0
    container_name: appointmentservice
    depends_on:
      - kong-database
      - kong-migration
      - kong
    environment:
      - appointment_serviceURL=mysql+mysqlconnector://is213@host.docker.internal:3306/appointment_service
    networks:
      - kong-net
      
  account_service:
    build: ./account_service
    image: account_service:1.0.0
    container_name: accountservice
    depends_on:
      - kong-database
      - kong-migration
      - kong
    environment:
      - account_serviceURL=mysql+mysqlconnector://is213@host.docker.internal:3306/account_service
    networks:
      - kong-net

  cart_service:
    build: ./cart_service
    image: cart_service:1.0.0
    container_name: cartservice
    depends_on:
      - kong-database
      - kong-migration
      - kong
    environment:
      - cart_serviceURL=mysql+mysqlconnector://is213@host.docker.internal:3306/cart_service
    networks:
      - kong-net

  tutor_service:
    build: ./tutor_service
    image: tutor_service:1.0.0
    container_name: tutorservice
    depends_on:
      - kong-database
      - kong-migration
      - kong
    environment:
      - tutor_serviceURL=mysql+mysqlconnector://is213@host.docker.internal:3306/tutor_service
    networks:
      - kong-net 

  payment_service:
    build: ./payment_service
    image: payment_service:1.0.0
    container_name: paymentservice
    depends_on:
      - kong-database
      - kong-migration
      - kong
    environment:
      - payment_serviceURL=mysql+mysqlconnector://is213@host.docker.internal:3306/payment_service
    networks:
      - kong-net

  appointment_queue:
    build: ./appointment_queue
    image: appointment_queue:1.0.0
    container_name: appointmentqueue
    depends_on:
      - kong-database
      - kong-migration
      - kong
    networks:
      - kong-net

  notification_queue:
    build: ./notification_queue
    image: notification_queue:1.0.0
    container_name: notificationqueue
    depends_on:
      - kong-database
      - kong-migration
      - kong
    networks:
      - kong-net

  notification:
    build: ./gmailApi
    image: notification_service:1.0.0
    container_name: notificationservice
    depends_on:
      - kong-database
      - kong-migration
      - kong
    networks:
      - kong-net
  
 

volumes:
  pgdata:
  kongadata:

 
  # searchcar:
  #   build: ./searchcar
  #   image: searchcar:1.0.0
  #   container_name: searchcar1
 
  # bookcar:
  #   build: ./bookcar
  #   image: bookcar:1.0.0
  #   container_name: bookcar1
 
  # googlematrix:
  #   build: ./googlematrix
  #   image: googlematrix:1.0.0
  #   container_name: googlematrix
